/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int EXEC = 12;
  /** RegularExpression Id. */
  int NEW = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int MACRO = 15;
  /** RegularExpression Id. */
  int OPEN_BRACE = 16;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int FI = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int OD = 25;
  /** RegularExpression Id. */
  int REP = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int PER = 28;
  /** RegularExpression Id. */
  int LEFT = 29;
  /** RegularExpression Id. */
  int FRONT = 30;
  /** RegularExpression Id. */
  int BACK = 31;
  /** RegularExpression Id. */
  int BACKWARDS = 32;
  /** RegularExpression Id. */
  int NORTH = 33;
  /** RegularExpression Id. */
  int SOUTH = 34;
  /** RegularExpression Id. */
  int EAST = 35;
  /** RegularExpression Id. */
  int WEST = 36;
  /** RegularExpression Id. */
  int FORWARD = 37;
  /** RegularExpression Id. */
  int WALK = 38;
  /** RegularExpression Id. */
  int JUMP = 39;
  /** RegularExpression Id. */
  int DROP = 40;
  /** RegularExpression Id. */
  int GRAB = 41;
  /** RegularExpression Id. */
  int LETGO = 42;
  /** RegularExpression Id. */
  int MOVES = 43;
  /** RegularExpression Id. */
  int NOP = 44;
  /** RegularExpression Id. */
  int SAFEEXE = 45;
  /** RegularExpression Id. */
  int TRUE = 46;
  /** RegularExpression Id. */
  int FALSE = 47;
  /** RegularExpression Id. */
  int TURNTOMY = 48;
  /** RegularExpression Id. */
  int TURNTOTHE = 49;
  /** RegularExpression Id. */
  int ISBLOCKED = 50;
  /** RegularExpression Id. */
  int ISFACING = 51;
  /** RegularExpression Id. */
  int ZERO = 52;
  /** RegularExpression Id. */
  int NOT = 53;
  /** RegularExpression Id. */
  int NUM = 54;
  /** RegularExpression Id. */
  int DIGIT = 55;
  /** RegularExpression Id. */
  int BALLOONS = 56;
  /** RegularExpression Id. */
  int CHIPS = 57;
  /** RegularExpression Id. */
  int NOMBRE = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Move\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"EXEC\"",
    "\"NEW\"",
    "\"VAR\"",
    "\"MACRO\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fi\"",
    "\"while\"",
    "\"do\"",
    "\"od\"",
    "\"rep\"",
    "\"times\"",
    "\"per\"",
    "\"left\"",
    "\"front\"",
    "\"back\"",
    "\"backwards\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"forward\"",
    "\"walk\"",
    "\"jump\"",
    "\"drop\"",
    "\"grab\"",
    "\"letGo\"",
    "\"moves\"",
    "\"nop\"",
    "\"safeExe\"",
    "\"true\"",
    "\"false\"",
    "\"turnToMy\"",
    "\"turnToThe\"",
    "\"isBlocked?\"",
    "\"isFacing?\"",
    "\"zero?\"",
    "\"not\"",
    "<NUM>",
    "<DIGIT>",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NOMBRE>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
